### ISSUE TITLE
NoneType not scriptable error

### ISSUE THREAD

**Issue by TotalChaos05** [yyyyyyyan/bandcamper#5]
i get this error after running
`bandcamper "https://peachringsnc.bandcamp.com/album/october-again`

`Traceback (most recent call last):
  File "/usr/local/bin/bandcamper", line 8, in <module>
    sys.exit(main())
  File "/home/basilk/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/basilk/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/basilk/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/basilk/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/bandcamper/__main__.py", line 180, in main
    bandcamp_downloader.download_all(destination, output, output_extra, *audio_formats)
  File "/usr/local/lib/python3.9/site-packages/bandcamper/bandcamper.py", line 355, in download_all
    self.download_from_url(
  File "/usr/local/lib/python3.9/site-packages/bandcamper/bandcamper.py", line 266, in download_from_url
    music_data = self._get_music_data(url)
  File "/usr/local/lib/python3.9/site-packages/bandcamper/bandcamper.py", line 137, in _get_music_data
    soup.find("script", {"data-tralbum": True})["data-tralbum"]
TypeError: 'NoneType' object is not subscriptable`

**Comment by yyyyyyyan** [comment]
Are you closing the quotes? ` bandcamper "https://peachringsnc.bandcamp.com/album/october-again"`
I could not reproduce this error.

**Comment by TotalChaos05** [comment]
Maybe it fixed itself?
I remade my server recently so i cant check in that environment, but it works now
